name: nNollisPluginsConnector
version: '1.0.0'
main: pl.nollis.connector.NollisPluginsConnector
api-version: '1.21'
depend: []
softdepend: [TowerPvP, CaveWars, SecureLogin]
authors: [Nollis]
description: |
  Multi-game mode connector plugin
  Manages main spawn and game mode selection

commands:
  spawn:
    description: Teleport to main spawn
    usage: /spawn
  lobby:
    description: Teleport to TowerPvP lobby
    usage: /lobby
  hub:
    description: Teleport to TowerPvP lobby
    usage: /hub
  nreload:
    description: Reload plugin configuration
    usage: /nreload
    permission: nollisconnector.admin
  party:
    description: Party management commands
    usage: |
      /party create - Create a party
      /party invite <player> - Invite player
      /party accept <leader> - Accept invite
      /party kick <player> - Kick player
      /party leave - Leave party
      /party list - List members
      /party disband - Disband party

permissions:
  nollisconnector.spawn:
    description: Use /spawn command
    default: true
  nollisconnector.lobby:
    description: Use /lobby and /hub commands
    default: true
  nollisconnector.party:
    description: Use party commands
    default: true
  nollisconnector.admin:
    description: Admin permissions (bypass lobby protection)
    default: op
